<a href="https://colab.research.google.com/github/sidhyaashu/DL_Computer_Vision/blob/master/tensors_variables_d1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [4]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5,6])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
    [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
],
    [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
],[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
]
])

print(tensor_four_d.ndim)

4


# Convert Numpy To Tensor

In [1]:
import numpy as np


In [2]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [5]:
converted_array = tf.convert_to_tensor(np_array)
print(converted_array)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [6]:
#Construct an identity matrix https://www.tensorflow.org/api_docs/python/tf/eye
eye_tensor = tf.eye(
    4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [9]:
eye_tensor = tf.eye(
    4,
    num_columns=None,
    batch_shape=[4,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(4, 4, 4), dtype=float32)


In [10]:
#Creates a tensor filled with a scalar value. https://www.tensorflow.org/api_docs/python/tf/fill
"""tf.fill(
    dims, value, name=None, layout=None
)"""

fill_tensor = tf.fill(
    [3,4], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [11]:
#Creates a tensor with all elements set to one (1). https://www.tensorflow.org/api_docs/python/tf/ones
tf_ones = tf.ones(
    [3,2,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(tf_ones)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 2, 3), dtype=float32)


In [13]:
#Creates a tensor of all ones that has the same shape as the input. https://www.tensorflow.org/api_docs/python/tf/ones_like

tf_ones_like = tf.ones_like(
    tf_ones, dtype=None, name=None, layout=None
)

print( tf_ones_like)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 2, 3), dtype=float32)


# Another methods are
zeros,
zeros_like,
shap,
Rank,
size