<a href="https://colab.research.google.com/github/sidhyaashu/DL_Computer_Vision/blob/master/tensors_variables_d1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

https://www.tensorflow.org/api_docs/python/tf

In [4]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,4,5,6])
print(tensor_one_d)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
    [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
],
    [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
],[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
]
])

print(tensor_four_d.ndim)

4


# Convert Numpy To Tensor

In [1]:
import numpy as np


In [2]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [5]:
converted_array = tf.convert_to_tensor(np_array)
print(converted_array)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [6]:
#Construct an identity matrix https://www.tensorflow.org/api_docs/python/tf/eye
eye_tensor = tf.eye(
    4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [9]:
eye_tensor = tf.eye(
    4,
    num_columns=None,
    batch_shape=[4,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(4, 4, 4), dtype=float32)


In [10]:
#Creates a tensor filled with a scalar value. https://www.tensorflow.org/api_docs/python/tf/fill
"""tf.fill(
    dims, value, name=None, layout=None
)"""

fill_tensor = tf.fill(
    [3,4], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [11]:
#Creates a tensor with all elements set to one (1). https://www.tensorflow.org/api_docs/python/tf/ones
tf_ones = tf.ones(
    [3,2,3],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)

print(tf_ones)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 2, 3), dtype=float32)


In [13]:
#Creates a tensor of all ones that has the same shape as the input. https://www.tensorflow.org/api_docs/python/tf/ones_like

tf_ones_like = tf.ones_like(
    tf_ones, dtype=None, name=None, layout=None
)

print( tf_ones_like)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 2, 3), dtype=float32)


# Another methods are
zeros,
zeros_like,
shap,
Rank,
size

# Random Normal Distribution

In [14]:
# https://www.tensorflow.org/api_docs/python/tf/random

In [16]:
# Outputs random values from a normal distribution.
# https://www.acsu.buffalo.edu/~adamcunn/probability/normal.html  playGround normal distribution

tf_normal_random = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(tf_normal_random)

tf.Tensor(
[[-0.23784274  1.040484  ]
 [ 0.6539853  -1.693266  ]
 [-1.6516482  -1.5349246 ]], shape=(3, 2), dtype=float32)


# INDEXING

In [17]:
tensor_index = tf.constant([1,2,3,4,5,6])
print(tensor_index)
print(tensor_index[1:4])

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [18]:
tf.range( 1,10)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [23]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d[:2 ,:2 ])
print("\n")
print(tensor_two_d[2 ,:2 ])
print("\n")
print(tensor_two_d[2 ,2 ])
print("\n")
print(tensor_two_d[:,2 ])

tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


tf.Tensor([7 8], shape=(2,), dtype=int32)


tf.Tensor(9, shape=(), dtype=int32)


tf.Tensor([3 6 9], shape=(3,), dtype=int32)


# MATH

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/math

In [24]:
# Computes the absolute value of a tensor.
x = -5
print(
    tf.math.abs(
    x, name=None
)
)



tf.Tensor(5, shape=(), dtype=int32)


In [25]:
# omputes the power of one value to another.
print(
    tf.math.pow(
    2, 3, name=None
)
)


tf.Tensor(8, shape=(), dtype=int32)


In [26]:
# Computes a safe divide which returns 0 if y (denominator) is zero.
print(
    tf.math.divide_no_nan(
    1.0, 0.0
)
)


tf.Tensor(0.0, shape=(), dtype=float32)


In [27]:
# Divides x / y elementwise, rounding toward the most negative integer.
print(
    tf.math.floordiv(
    10, 3, name=None
)
)

tf.Tensor(3, shape=(), dtype=int32)


In [32]:
# Returns the index with the largest value across axes of a tensor.  https://www.tensorflow.org/api_docs/python/tf/math/argmax

x_argmax = tf.math.argmax(
    [
    [1,10,3],
    [4,5,6],
    [7,8,9]
]
)

print(x_argmax.shape)
print(x_argmax,0)

(3,)
tf.Tensor([2 0 2], shape=(3,), dtype=int64) 0


In [34]:
x_argmax = tf.math.argmax(
    [
    [1,10,3],
    [4,5,6],
    [7,28,9]
],
    axis=1
)

print(x_argmax)

tf.Tensor([1 2 1], shape=(3,), dtype=int64)


# Linear algebra

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/linalg

In [45]:
# prompt: Give tensorflow linalg package all methods implemented in example

# Matrix multiplication
matrix_u = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix_v = tf.constant([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
mat_mul = tf.linalg.matmul(
    matrix_u,
    matrix_v,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    name=None
)
print(mat_mul)
# Computes the determinant of one or more square matrices.
matrix_2_2 = tf.constant([
    [1,2],
    [3,4]
], dtype=tf.float32)
print(tf.linalg.det(matrix_2_2))
# Computes the sign and the log of the absolute value of the determinant of one or more square matrices.
sign , log_abs_det  = tf.linalg.slogdet(
    matrix_2_2, name=None
)
print(sign,log_abs_det)
# Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
matrix_inv = tf.linalg.inv(
    matrix_2_2, adjoint=False, name=None
)
print(matrix_inv)
# Solves systems of linear equations.
x = tf.linalg.solve(
    matrix_2_2,
    [
        [1,0],
        [0,1]
    ],
    adjoint=False, name=None
)
print(x)
# Computes the eigenvalues of one or more matrices.
e , v = tf.linalg.eig(
    matrix_2_2, name=None
)
print(e,v)
# Computes the singular value decompositions of one or more matrices.
s,u,v = tf.linalg.svd(
    matrix_2_2, full_matrices=False, compute_uv=True, name=None
)
print(s,u,v)
# QR Decomposition
q,r = tf.linalg.qr(
    matrix_2_2, full_matrices=False, name=None
)
print(q,r)


tf.Tensor(
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]], shape=(3, 3), dtype=int32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32) tf.Tensor(0.6931472, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
tf.Tensor([-0.37228122+0.j  5.372281  +0.j], shape=(2,), dtype=complex64) tf.Tensor(
[[-0.8245648 +0.j -0.41597357+0.j]
 [ 0.56576747+0.j -0.90937674+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32) tf.Tensor(
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]], shape=(2, 2), dtype=float32) tf.Tensor(
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.3162278  -0.9486833 ]
 [-0.9486833   0.31622773]], shape=(2, 2), dtype=float32) tf.Tensor(
[[-3.1622777  -4.4271884 ]
 [ 0.         -0.63245535]]

# Sparse Tensor

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/linalg/band_part

In [44]:
# prompt: what is sparse tensor

# Sparse Tensor
# A sparse tensor is a tensor that has a majority of its elements as zero.
# This allows for efficient storage and computation, as only the non-zero elements and their indices need to be stored.


In [ ]:


# Create a sparse tensor
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]],
    values=[1, 2],
    dense_shape=[3, 4]
)

# Convert to dense tensor
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print(dense_tensor)

# Sparse matrix multiplication
sparse_matrix_a = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 1]],
    values=[1, 2],
    dense_shape=[2, 2]
)
dense_matrix_b = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
result = tf.sparse.sparse_dense_matmul(sparse_matrix_a, dense_matrix_b)
print(result)


In [ ]:
# Copy a tensor setting everything outside a central band in each innermost matrix to zero.

In [ ]:
tf.linalg.band_part(
    input: Annotated[Any, TV_MatrixBandPart_T],
    num_lower: Annotated[Any, TV_MatrixBandPart_Tindex],
    num_upper: Annotated[Any, TV_MatrixBandPart_Tindex],
    name=None
) -> Annotated[Any, TV_MatrixBandPart_T]



The band part is computed as follows: Assume input has k dimensions [I, J, K, ..., M, N], then the output is a tensor with the same shape where

band[i, j, k, ..., m, n] = in_band(m, n) * input[i, j, k, ..., m, n].

The indicator function

in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).

In [ ]:
# if 'input' is [[ 0,  1,  2, 3]
#                [-1,  0,  1, 2]
#                [-2, -1,  0, 1]
#                [-3, -2, -1, 0]],

In [48]:
input = tf.constant([
    [ 0,  1,  2, 3],
                [-1,  0,  1, 2],
                [-2, -1,  0, 1],
                [-3, -2, -1, 0]])

In [51]:
tf.linalg.band_part(input, 1, -1)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [ 0, -1,  0,  1],
       [ 0,  0, -1,  0]], dtype=int32)>

In [ ]:
#  tf.linalg.band_part(input, 0, -1) ==> Upper triangular part.
#  tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
#  tf.linalg.band_part(input, 0, 0) ==> Diagonal.

In [52]:
tf.linalg.band_part(input, 0, -1)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [0, 0, 1, 2],
       [0, 0, 0, 1],
       [0, 0, 0, 0]], dtype=int32)>

In [54]:
tf.linalg.band_part(input, -1, 0)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  0,  0,  0],
       [-1,  0,  0,  0],
       [-2, -1,  0,  0],
       [-3, -2, -1,  0]], dtype=int32)>

In [55]:
tf.linalg.band_part(input, 0, 0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).

In [56]:
# https://www.tensorflow.org/api_docs/python/tf/linalg/inv

In [65]:

# Define a square invertible matrix
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

# Compute the inverse of the matrix
inverse_matrix = tf.linalg.inv(matrix)

# Print the inverse matrix
print(inverse_matrix)


tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
